### ISSUE TITLE
Use stdlib fallible alllocation primitives

### ISSUE THREAD

**Issue by baumanj** [vcombey/fallible_collections#23]
Rust 1.57 stabilized [stdlib fallible allocation](https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#fallible-allocation), so it would be beneficial to replace the relevant code in this crate to use the stdlib where possible. I still think there's a lot of value in the distinct fallible collection types, however, since the stdlib collections require calling the fallible reserve functions appropriately to avoid infallible allocations.

**Comment by kornelski** [comment]
Done in #24

**Comment by baumanj** [comment]
Awesome! Thanks @kornelski
