### ISSUE TITLE
Make hashbrown dependency optional

### ISSUE THREAD

**Issue by cccs-ki** [vcombey/fallible_collections#32]
I'd like to use the Box part of this library, however I don't want to bring in any dependencies. I think there should be a feature called "hashmap" which gets added to the default features, but is required to use hashbrown and the hashmap functionality. 

Thus, removing the feature should remove hashbrown as a dependency.

**Comment by baumanj** [comment]
Hashbrown is already the default for rust stdlib, so unless you’re using nostd, it’s not adding any new dependencies
