### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by danielstuart14** [vcombey/fallible_collections#52]
Hi there, 
   As Rust std/core collections still don't support fallible allocations, this library is still quite important for the language ecosystem as a whole. With the rapid rampage of Rust use on embedded systems, it is even more critical to have collections with fallible allocation supported.

   @vcombey It would be nice to have a status of the project, as well as if you need any help maintaining it.
   
   Thanks in advance; this is an awesome library you have here!

**Comment by vcombey** [comment]
Hi,
I've just released version 0.5.1, incorporating the recent pull requests.
Apologies for leaving some PRs unattended; they slipped my mind. If this happens again, please feel free to ping me.
Although I don't have much time for new development, I'm available for reviewing PRs and handling releases.
Though I don't feel entirely competent reviewing the most obscure PRs. If anyone is interested in helping out with those, I can add him as a maintainer

**Comment by danielstuart14** [comment]
Hey @vcombey, I'll get in contact with you through email; maybe we can work something out to better structure the project and alleviate the burden of reviewing PRs.
